name: version-update

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      dry-run:
        type: boolean
        default: false
    secrets:
      BOT_PRIVATE_KEY:
        required: true
    outputs:
      current-version:
        value: ${{ jobs.bump-version.outputs.current-version }}
      next-major-tag:
        value: ${{ jobs.bump-version.outputs.next-major-tag }}
      next-minor-tag:
        value: ${{ jobs.bump-version.outputs.next-minor-tag }}
      next-patch-tag:
        value: ${{ jobs.bump-version.outputs.next-patch-tag }}
      change:
        value: ${{ jobs.bump-version.outputs.change }}
      update-sha:
        value: ${{ jobs.bump-version.outputs.update-sha }}

permissions:
  contents: write
  id-token: write
  pull-requests: read

env:

  DRY_RUN: ${{ inputs.dry-run && 'true' || 'false' }}
  DRY_RUN_FLAG: ${{ inputs.dry-run && ' --dry-run ' || ' ' }}

jobs:

  bump-version:
    runs-on: ubuntu-latest
    outputs:
      current-version: ${{ steps.config-version.outputs.version }}
      next-major-tag: ${{ steps.output-tags.outputs.MAJOR }}
      next-minor-tag: ${{ steps.output-tags.outputs.MINOR }}
      next-patch-tag: ${{ steps.output-tags.outputs.PATCH }}
      change: ${{ steps.output-tags.outputs.change }}
      update-sha: ${{ steps.commit.outputs.commit-hash }}
    steps:
      -
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      -
        uses: actions/checkout@v5
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0
      -
        name: Store commit message
        id: commit-message
        run: |
          {
            echo "hash=$(git show ${{ github.sha }} --no-patch --format='%h')"
            echo 'message<<EOT';
            git show --format='%s' --no-patch;
            echo 'EOT';
          } | tee -a "$GITHUB_OUTPUT"
      -
        name: Read version from manifest.json
        id: config-version
        run: |
          MANIFEST_VERSION=$(jq -r '.version' ./custom_components/smart_switch/manifest.json)
          echo "version=$MANIFEST_VERSION" | tee -a "$GITHUB_OUTPUT"
      -
        name: Determine version format
        id: version-format
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          VERSION_FORMAT='${major}.${minor}.${patch}'

          if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            VERSION_FORMAT='${major}.${minor}.${patch}-pr'"${PR_NUMBER}"'-${increment}'
          fi

          echo "version_format=$VERSION_FORMAT" | tee -a "$GITHUB_OUTPUT"
      -
        name: Compute next version
        id: version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: v
          bump_each_commit: true
      -
        name: Construct version tags
        id: output-tags
        run: |
          LATEST_MAJOR="${{ steps.version.outputs.major }}"
          LATEST_MINOR="${LATEST_MAJOR}.${{ steps.version.outputs.minor }}"
          LATEST_PATCH="${LATEST_MINOR}.${{ steps.version.outputs.patch }}"

          echo "::notice::Detected version: ${LATEST_PATCH}"

          {
            echo "MAJOR=v$LATEST_MAJOR";
            echo "MINOR=v$LATEST_MINOR";
            echo "PATCH=v$LATEST_PATCH";
          } | tee -a "$GITHUB_OUTPUT" "$GITHUB_ENV"

          if [[ "$LATEST_PATCH" == "${{ steps.config-version.outputs.version }}" ]]; then
            echo "change=false" | tee -a "$GITHUB_OUTPUT"
          else
            echo "change=true" | tee -a "$GITHUB_OUTPUT"
          fi
      -
        name: Fetch GitHub App identity
        id: app-identity
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          APP_USER=$(gh api /users/${{ vars.BOT_APP_ID }}[bot] --jq '.login')
          APP_EMAIL="${APP_USER}@users.noreply.github.com"

          {
            echo "user=$APP_USER"
            echo "email=$APP_EMAIL"
          } | tee -a "$GITHUB_OUTPUT"
      -
        name: Configure git
        run: |
          git config --global user.name "${{ steps.app-identity.outputs.user }}"
          git config --global user.email "${{ steps.app-identity.outputs.email }}"

          echo "Configured git as: ${{ steps.app-identity.outputs.user }} <${{ steps.app-identity.outputs.email }}>"
      -
        name: Checkout ref for commit
        run: |
          # Checkout current ref
          git fetch --all
          git checkout "${{ github.head_ref || github.ref_name }}"
      -
        name: Update manifest files
        env:
          VERSION_TAG: ${{ steps.output-tags.outputs.PATCH }}
        run: |
          while IFS='' read -r component || [[ -n "$component" ]]; do
            MANIFEST_FILE="custom_components/$component/manifest.json"

            WITHOUT_PREFIX="${VERSION_TAG#v}"
            MANIFEST_JSON=$(jq -r \
              --arg version "$WITHOUT_PREFIX" \
              '.version = $version' \
              "$MANIFEST_FILE")

            printf '%s' "$MANIFEST_JSON" > "$MANIFEST_FILE"
          done < <(ls -1 custom_components)
      -
        name: Update CHANGELOG.md
        env:
          VERSION_TAG: ${{ steps.output-tags.outputs.PATCH }}
          COMMIT_MESSAGE: '[`${{ steps.commit-message.outputs.hash }}`](${{ github.server_url }}/${{ github.repository }}/commit/${{ steps.commit-message.outputs.hash }}) ${{ steps.commit-message.outputs.message }}'
        run: |
          ./scripts/changelog.sh \
            | tee CHANGELOG.md
      -
        name: "Commit changes and push (DRY_RUN=${{ env.DRY_RUN }})"
        id: commit
        run: |
          git add .
          git commit -m "[bot] ${PATCH}"

          # Output commit hash
          COMMIT_HASH=$(git show --no-patch --format="%h")
          echo "commit-hash=$COMMIT_HASH" | tee -a "$GITHUB_OUTPUT"

          # push commit
          if [[ "${DRY_RUN}" == "true" ]]; then
            echo "Skipping pushing changes, due to dry run"
          else
            git push --force
          fi

      -
        name: "Update tags (DRY_RUN=${{ env.DRY_RUN }})"
        run: |
          git tag "$PATCH"

          tags=("$MAJOR" "$MINOR" "$PATCH")

          for tag in "${tags[@]}"; do
            echo "::group::Pointing tag ${tag} to ${{ steps.commit.outputs.commit-hash }}"
            
            # Delete the remote tag
            if [[ "${DRY_RUN}" == "true" ]]; then
              echo "Skipping deleting remote tag origin/$tag, due to dry run"
            else
              git push \
                --delete \
                origin "$tag" \
              || true
            fi

            # Delete the local tag
            if [[ "${DRY_RUN}" == "true" ]]; then
              echo "Skipping deleting local tag $tag, due to dry run"
            else
              git tag \
                --delete \
                "$tag" \
                2> /dev/null \
              || true
            fi
            
            # Create a new tag :)
            if [[ "${DRY_RUN}" == "true" ]]; then
              echo "Skipping creating a new tag $tag, due to dry run"
            else
              git tag "$tag"
            fi

            echo "::endgroup::"
          done

          if [[ "${DRY_RUN}" == "true" ]]; then
            echo "Skipping pushing updates, due to dry run"
          else
            git push --tags
          fi
      -
        name: Release
        if: ${{ github.event_name != 'pull_request' && !inputs.dry-run }}
        env:
          GH_TOKEN: ${{ github.token }}
          NOTES_START_TAG: v${{ steps.version.outputs.previous_version }}
        run: |
          if [[ $(gh release view "${PATCH}" > /dev/null) ]]; then
            gh release delete "${PATCH}" -y
          fi

          gh release create ${PATCH} \
            --title "${PATCH}" \
            --generate-notes \
            --notes-start-tag "${NOTES_START_TAG}"
